### ISSUE TITLE
use UUID when generating ID instead of simple alphanumeric string

### ISSUE THREAD

**Issue by ewaldorf** [GS1Brasil/HCHorizontalCommunication#2]
Currently, id type as an alphanumeric string as shown below:
<xs:simpleType name="id">
        <xs:annotation>
			<xs:documentation>id field use in each message inside the schema.</xs:documentation>
		</xs:annotation>
        <xs:restriction base="xs:string">
            <xs:maxLength value="50" />
            <xs:pattern value="[A-Z][0-9]" />
        </xs:restriction>
    </xs:simpleType>

ids are assigned to InboundMessage, AttorneyAuthorization, InboundResponse, PreferenceData, QueryRequest, QueryResponse

Recommendation: Instead of defining ID as alphanumeric string, define ID as Universal Unique Identifier (UUID) version 4 to ensure universal uniqueness.

**Comment by rodrigoklein** [comment]
@ewaldorf ,
please confirm to us if this string below meet your expectation.
8f86faf9-f1f1-4b43-893a-614de3ff752d
It was generated using UUID4
Thanks

**Comment by ewaldorf** [comment]
8f86faf9-f1f1-4b43-893a-614de3ff752d is a valid example of UUID version 4
here's the regular expression pattern": "^[a-fA-F\\d]{8}-[a-fA-F\\d]{4}-4[a-fA-F\\d]{3}-[89abAB][a-fA-851 F\\d]{3}-[a-fA-F\\d]{12}"

**Comment by rodrigoklein** [comment]
Hi @ewaldorf ,
I have updated the schemas and samples with the new IDs based on UUID4 asked by you.
Thanks for your cooperation.
